version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    image: homecolis-api/latest
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_HOST=mongo_DB
      - MONGO_USER=admin
      - MONGO_DATABASE=admin
      - MONGO_PASSWORD=123456
  mongo:
    image: mongo:latest
    container_name: mongo_DB
    environment:
      - MONGO_HOST=127.0.0.1
      - MONGO_DATABASE=admin
    volumes:
      - ./data:/data/db
    command: --auth  
    ports:
      - "27017:27017"
